version: '3.9'
services:
  run:
    depends_on:
      - ev1
      - ev1x
      - ev1y
    container_name: ev1
    image: nginx:1.21.4-alpine
    command:
      - nginx-debug
      - -g
      - daemon off;
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ev1/dist:/app/ev1:ro
      - ./ev1x/dist:/app/ev1x:ro
      - ./ev1y/dist:/app/ev1y:ro
  ev1:
    container_name: build-ev1
    image: node:14.18.1-alpine3.14
    command:
      - sh
      - -c
      - |
        yarn
        yarn build
    volumes:
      - ./ev1/dist:/app/ev1
    working_dir: /app/ev1
  ev1x:
    container_name: build-ev1x
    image: node:14.18.1-alpine3.14
    command:
      - sh
      - -c
      - |
        yarn
        yarn build
    volumes:
      - ./ev1x/dist:/app/ev1x
    working_dir: /app/ev1x
  ev1y:
    container_name: build-ev1y
    image: node:14.18.1-alpine3.14
    command:
      - sh
      - -c
      - |
        yarn
        yarn build
    volumes:
      - ./ev1y/dist:/app/ev1y
    working_dir: /app/ev1y