name: Deploy feature branch for personal environment

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/ghilbut-ev1x-default.yml
      - spa-examples/vue.js/ev1x/public/**
      - spa-examples/vue.js/ev1x/src/**
      - spa-examples/vue.js/ev1x/test/**
      - spa-examples/vue.js/ev1x/package.json
      - spa-examples/vue.js/ev1x/tsconfig.json
      - spa-examples/vue.js/ev1x/yarn.lock

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./spa-examples/vue.js/ev1x

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Check node_module cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ env.WORKDIR }}/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('${{ env.WORKDIR }}/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn build
        id: yarn-build
        run: |
          tee .env.local << EOF
          BASE_URL=/x
          EOF
          yarn
          yarn build
        working-directory: ${{ env.WORKDIR }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:            us-east-1
          aws-access-key-id:     ${{ secrets.GHILBUT_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GHILBUT_AWS_SECRET_KEY }}

      - name: Deploy main branch
        if:   github.ref == 'refs/heads/main'
        env:
          HOST: ev1.c.ghilbut.com
        run: |
          aws s3 sync \
            ./dist s3://ghilbut-cdn-for-preview-virginia/${HOST}/x \
            --delete
          aws s3 cp \
            s3://ghilbut-cdn-for-preview-virginia/${HOST}/x \
            s3://ghilbut-cdn-for-preview-virginia/${HOST}/x \
            --recursive \
            --exclude "*" \
            --include "index.html" \
            --metadata-directive REPLACE \
            --cache-control max-age=0,must-revalidate,public \
            --content-type "text/html; charset=utf-8"
        working-directory: ${{ env.WORKDIR }}

      - name: Deploy develop branch
        if:   github.ref == 'refs/heads/develop'
        env:
          HOST: ev1.s.ghilbut.com
        run: |
          aws s3 sync \
            ./dist s3://ghilbut-cdn-for-preview-virginia/${HOST}/x \
            --delete
        working-directory: ${{ env.WORKDIR }}
